# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-16 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250)),
                ('dept', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250)),
                ('dept', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stud_Faculty_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_approval', models.BooleanField(default=False)),
                ('faculty_remarks', models.CharField(blank=True, max_length=250)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stud')),
            ],
        ),
        migrations.AddField(
            model_name='stud',
            name='faculty_approval',
            field=models.ManyToManyField(through='main.Stud_Faculty_Status', to='main.Faculty'),
        ),
    ]
