# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assistantRegistrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Assi. Registrar', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250)),
                ('hostel', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
                ('department', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='warden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250)),
                ('hostel', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
