# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_assistantregistrar_caretaker_hod_lab_warden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stud_Lab_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_approval', models.BooleanField(default=False)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lab')),
            ],
        ),
        migrations.RemoveField(
            model_name='stud',
            name='dept',
        ),
        migrations.AddField(
            model_name='caretaker',
            name='password',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='stud',
            name='CC_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stud',
            name='HOD_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stud',
            name='account_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stud',
            name='assistant_registrar_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stud',
            name='caretaker_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stud',
            name='department',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='stud',
            name='gymkhana_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stud',
            name='hostel',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='stud',
            name='library_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stud',
            name='online_cc_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stud',
            name='password',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='stud',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stud',
            name='submit_thesis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stud',
            name='warden_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warden',
            name='password',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='stud',
            name='webmail',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='stud_lab_status',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stud'),
        ),
        migrations.AddField(
            model_name='stud',
            name='lab_approval',
            field=models.ManyToManyField(through='main.Stud_Lab_Status', to='main.lab'),
        ),
    ]
