# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171224_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='dept',
            new_name='department',
        ),
    ]
