# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171224_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Account', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='cc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Computer Center', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='gymkhana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gymkhana', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Library', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='onlineCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='OnlineCC Manager', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='submitThesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Thesis Manager', max_length=250)),
                ('webmail', models.CharField(blank=True, max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
